name: dart
description: A new Web Flutter project with BLOC.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  go_router: ^7.0.0
  logger: ^1.3.0
  provider: ^6.0.5
  responsive_framework: ^1.0.0
  shared_preferences: ^2.1.0
  timezone: any
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/socials/
